version: '3'

services:
#  app:
#    container_name: "bili-app"
#    links:
#      - db
#      - redis
#    depends_on:
#      - db
#      - redis
#    ports:
#      - '8080:8080'
#    build: "./"
#    volumes:
#      - ./:/go/src/bili
  db:
    container_name: "pennant-db"
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: "pennant-user"
      MYSQL_PASSWORD: "pennant-pass"
      MYSQL_DATABASE: "pennant"
