version: '3'

services:
  pennant-admin-backend:
    container_name: "pennant-admin-backend"
    links:
      - pennant-flagger
    depends_on:
      - pennant-flagger
    ports:
      - '8080:8080'
    build: "./deployments/submodules/pennant-admin-backend/deployment"
    volumes:
    - ./deployments/submodules/pennant-admin-backend/:/app
    environment:
      SERVER_PORT: "8080"
      PENNANT_FLAGGER_HOST: "pennant-flagger"
      PENNANT_FLAGGER_PORT: "7777"
  pennant-admin-frontend:
    container_name: "pennant-admin-frontend"
    links:
      - pennant-admin-backend
    depends_on:
      - pennant-admin-backend
    ports:
      - '3000:3000'
    build: "./deployments/submodules/pennant-admin-frontend/deployment"
    volumes:
      - ./deployments/submodules/pennant-admin-frontend/:/app
    environment:
      PORT: "3000"
  pennant-flagger:
    container_name: "pennant-flagger"
    links:
      - db
    depends_on:
      - db
    ports:
      - '7777:7777'
    build: "./deployments/submodules/pennant-flagger/deployment"
    volumes:
      - ./deployments/submodules/pennant-flagger/:/app
    environment:
      SERVER_PORT: "7777"
      MYSQL_SCHEMA: "pennant"
      MYSQL_HOST: "db"
      MYSQL_PORT: "3306"
      SECRETS_FILE: "/app/secrets.json"
      MIGRATION_LOCATION: "db/migrations"
  db:
    container_name: "pennant-db"
    image: mysql:5.7
    ports:
      - '3306:3306'
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_USER: "pennant-user"
      MYSQL_PASSWORD: "pennant-pass"
      MYSQL_DATABASE: "pennant"
